import React from 'react'
import Navbar from '../Components/Navbar'
import Footer from '../Components/Footer'
import LinesHero from '../Components/LineHero'

const Sejarah: React.FC = () => {
  return (
    <div className='w-screen'>
        <Navbar />
        <div className='relative w-screen bg-[#913d88] h-[40vh] md:h-[60vh] flex items-center justify-center mb-4 md:mb-8'>
            <LinesHero />
            <h2 className='text-white mt-8 text-[36px] md:text-[36px] w-[80%] md:w-full text-center md:text-[60px]'>Sejarah Lemhannas RI</h2>
        </div>
        
        <div className='w-full h-max mb-6 p-4 md:p-10'>
            <h2 className='font-bold text-[24px] w-full md:text-[36px] mb-4'>1962-1964: Awal Pembentukan Lemhannas RI</h2>
            <p className='leading-loose w-full md:w-[80%]'>Panitia Interdepartemental yang dilantik pada tanggal 13 Desember 1962 ini menandakan wadah Lemhannas resmi telah ada. Panitia yang beranggotakan 16 orang yang dipimpin oleh Letjen TNI R. Hidayat ini bertugas untuk mempersiapkan suatu lembaga pendidikan tinggi pertahanan untuk membentuk dan mengembangtkan tenaga-tenaga pembina baik sipil maupun militer, pada tingkat politik strategi dan pertahanan nasional.</p>
            <p className='leading-loose w-full md:w-[80%]'>Selanjutnya, panitia Interdepartemental mengadakan rapat secara berkala untuk merumuskan karya tulis yang merumuskan segala hal tentang Lemhannas. Dalam rapat pada tanggal 12 Januari 1963 yang dipimpin oleh Ketua Panitia, beliau memberikan petunjuk untukmerumuskan hasil karya panitia. Beberapa petunjuk tersebut antara lain menyangkut penggunaan istilah “pertahanan”, bentuk kegiatan lembaga, dan falsafah yang melandasi kegiatan Lemhannas.</p>
            <p className='leading-loose w-full md:w-[80%]'>Rumusan hasil kegiatan Panitia Interdepartemental yang disampaikan secara lengkap kepada Menteri Pertama pada tanggal 7 Maret 1963 merumuskan bahwa kehadiran Lemhannas merupakan salah satu urgensi nasional dalam rangka menyelamatkan/melestarikan cita-cita Proklamasi Kemerdekaan serta tujuan Bangsa Indonesia dan terjaminnya kelangsungan hidup bangsa Indonesia di tengah percaturan politik dunia.</p>
            <p className='leading-loose w-full md:w-[80%]'>"Untuk merealisasi terwujudnya Lemhannas, Menko Hankam/Kasab membentuk Staf Pelaksanaan berikut Petunjuk Pelaksanaan pendirian Lemhannas. Staf Pelaksana Lemhannas yang tertuang dalam Surat Keputusan Menko Hankam/Kasab Nomor : M/E/1000/1964 tanggal 11 Juli 1964, diketuai oleh Mayjen TNI Wiluyo Puspoyudo dilantik pada 20 Juli 1964 Oleh Menko Hankam/KASAB A.H. Nasution. Di hari yang sama, dikeluarkan pula Petunjuk Pelaksanaan tentang Pendirian Lemhannas (Surat Keputusan Nomor III/E/77/1964 tanggal 20 Juli 1964) yang direncanakan bahwa peresmian pembukaan Lemhannas akan dikaitkan dengan peringatan Hari Pahlawan 10 November 1964. Namun akhirnya rencana tersebut harus mundur menjadi tanggal 20 Mei 1965, berkaitan dengan hari Kebangkitan Nasional.</p>
        </div>

        <div className='w-full h-max mb-6 p-4 md:p-10'>
            <h2 className='font-bold text-[24px] w-full md:text-[36px] mb-4'>1965: Semangat Kebangkitan Nasional, Semangat Pembentukan Lemhannas</h2>
            <p className='mb-4 w-full md:w-[80%]'>Berawal dari gagasan yang lahir dari keinginan luhur sejumlah perwira tinggi di staf keamanan nasional pada waktu itu, cita-cita pembentukan Lembaga Pertahanan Nasional (Lemhannas) bukan lagi hanya sekedar wacana. Melalui proses waktu, pemikiran dan konsepsi yang cukup panjang dan berliku, akhirnya bertepatan dengan momentum Hari Kebangkitan Nasional, Lemhannas diresmikan pada 20 Mei 1965. Kala itu sebutan Pertahanan Nasional, mengandung arti Ketahanan dari suatu bangsa yang sedang berevolusi.</p>
            <p className='mb-4 w-full md:w-[80%]'>Presiden Soekarno yang meresmikan Lemhannas di Istana Negara Jakarta  menekankan bahwa kegiatan pertahanan nasional harus menyertakan segenap unsur-unsur  rakyat Indonesia. Dalam amanat bertemakan ”Susunlah Pertahanan Nasional Bersendikan Karakter Bangsa”, Presiden juga menjelaskan arti kata “Nasional” dalam Lembaga Pertahanan Nasional, yakni pertahanan  bagi seluruh tanah air, seluruh natie, seluruh bangsa. “.....Kita punya pertahanan, cara pertahanan sendiri.....”, kembali ditegaskan oleh Presiden Soekarno saat itu. Usai upacara peresmian dan pembukaan KRA I tahun 1965, Presiden memberikan kuliah pertama tentang geo-politik.</p>
            <p className='mb-4 w-full md:w-[80%]'>Lemhannas yang dicita-citakan adalah sebuah institusi yang berorientasi  pada pencapaian tujuan nasional Indonesia. Selain itu, Lemhannas dirancang dan dipersiapkan sebagai pusat pendidikan dan pengkajian masalah-masalah strategis  berkaitan dengan pertahanan negara dalam arti luas, termasuk dalam pengendalian keutuhan bangsa. Dengan demikian, terlihat betapa penting dan strategisnya keberadaan Lemhannas.</p>
        </div>

        <div className='w-full h-max mb-6 p-4 md:p-10'>
            <h2 className='font-bold text-[24px] w-full md:text-[36px] mb-4'>1968-1969: Awal Perkembangan Konsep Tannas</h2>
            <p className='mb-4 w-full md:w-[80%]'>Perkembangan gagasan mengenai Ketahanan itu sendiri dimulai sejak tahun 60-an, yang dirintis oleh para perwira ABRI di Seskoad dan oleh peserta KRA I (1965) yang mengembangkan konsep berjudul KETAHANAN REVOLUSI.</p>
            <p className='mb-4 w-full md:w-[80%]'>Sejak awal pembentukannya gagasan pertama yang dihasilkan oleh Lemhannas adalah gagasan Ketahanan Nasional tahun 1968. Pusat perhatian gagasan Ketahanan Nasional (Tannas) pada waktu itu adalah hanya untuk mempertahankan kelangsungan hidup bangsa dan negara Indonesia, walaupun di bagian lain disinggung pertahanan bagi proses pertumbuhan bangsa dan negara.</p>
            <p className='mb-4 w-full md:w-[80%]'>Saat itu Lemhannas masih terus melakukan pengkajian untuk menyempurnakan gagasannya tersebut. Penyempurnaan baru dapat diselesaikan pada 1969, yang  menggariskan bahwa: “Ketahanan Nasional adalah keuletan dan daya tahan kita dalam menghadapi segala ancaman, baik yang datang dari luar maupun dari dalam, yang langsung maupun tidak langsung membahayakan kelangsungan hidup negara dan bangsa Indonesia”.</p>
        </div>

        <div className='w-full h-max mb-6 p-4 md:p-10'>
            <h2 className='font-bold text-[24px] w-full md:text-[36px] mb-4'>1971-1972: Perbaikan Organisasi dan Perkembangan Tannas</h2>
            <p className='mb-4 w-full md:w-[80%]'>Dalam perkembangannya yang memasuki tahun ke-6 sejak pembentukannya, perbaikan dan peningkatan organisasi terus dilakukan. Pada 1971, Gubernur Lemhannas dan stafnya mengunjungi institusi-institusi pertahanan yang terkenal seperti NDC (National Defence College), NWC (National War College) di pelbagai negara seperti USA, Inggris, Perancis, Belanda, Kanada, Jerman Barat dan juga Vietnam Selatan. Dengan pengalaman dan bahan-bahan yang diperoleh dari kunjungan tersebut, pada tahun 1972 dilakukan Reorganisasi dan Refungsionalisasi Lemhannas sesuai surat keputusan Menhankam/Pangab Nomor : Skep. a/21/V/1972 yang diantaranya menyebutkan bahwa:</p>
            <p className='mb-4 w-full md:w-[80%]'>Pertama, tugas pokok Lemhannas adalah membantu Menhankam/Pangab dalam usaha mencapai, mempertinggi dan memelihara Ketahanan Nasional dengan jalan membina terwujudnya integritas dan kerjasama dalam pengarahan dan penggunaan segenap unsur kekuatan dan potensi nasional. Sedangkan fungsi-fungsi utama Lemhannas adalah mengembangkan kemampuan manajemen tinggi para tenaga senior terpilih (militer dan sipil) yang akan berkecimpung dalam pembinaan politik dan strategi nasional; kedua, menyelenggarakan pengkajian-pengkajian bagi kepentingan nasional umumnya atas dasar pengarahan/instruksi Dephankam dan pertimbangan/keperluan Lemhannas sendiri.</p>
            <p className='mb-4 w-full md:w-[80%]'>Tidak hanya peningkatan organisasi saja, gagasan Tannas semakin berkembang pada tahun-tahun berikutnya. Gagasan Tannas pada tahun 1968 dan 1969, saat itu hanya ditujukan untuk Tannas Indonesia. Perkembangan gagasan Tannas tahun 1972 ditujukan atau berlaku bagi negara-negara yang sedang berkembang. Dalam pengertian Tannas tahun 1972 secara jelas dinyatakan pusat perhatian Tannas, yaitu untuk mempertahankan kelangsungan hidup bangsa dan negara serta untuk mengamankan perjuangan mengejar tujuan nasional.</p>
        </div>

        <div className='w-full h-max mb-6 p-4 md:p-10'>
            <h2 className='font-bold text-[24px] w-full md:text-[36px] mb-4'>1974-1978: Lemhannas Sebagai Lembaga Pengkajian dan Pendidikan Nasional Berdasarkan Konsepsi Tannas</h2>
            <p className='mb-4 w-full md:w-[80%]'>Berdasar Keputusan Presiden RI Nomor 7 tahun 1974 tanggal 18 Februari 1974, Lemhannas ditetapkan berkedudukan sebagai salah satu badan pelaksana Departemen Hankam yang membantu Menhankam/Pangab dalam usaha mencapai, mempertinggi dan memelihara Ketahanan Nasional dengan jalan membina terwujudnya integrasi dan kerjasama dalam pengerahan dan penggunaan segenap unsur kekuatan dan potensi nasional.</p>
            <p className='mb-4 w-full md:w-[80%]'>Sebagai penyempurnaan lebih lanjut dari Keppres Nomor 7 Tahun 1974, Menhankam/Pangab mengeluarkan keputusan Nomor: Kep/17/VII/1978 tanggal 28 Juli 1978 tentang pokok-pokok organisasi dan prosedur Lemhannas yang mengatur kedudukan Lemhannas sebagai suatu badan pelaksana pusat di tingkat departemen, kedudukan langsung dibawah Menhankam/Pangab, dalam pelaksanaan tugas sehari-hari dikoordinasikan oleh Wapangab. Selanjutnya pada tanggal 28 September 1979, Menhankam/Pangab mengeluarkan surat keputusan Nomor: Kep/25/IX/1979 sebagai penyempurnaan surat keputusan Menhankam/Pangab Nomor: Kep/17/VII/1978 tanggal 24 Juli 1978 tentang pokok-pokok organisasi dan prosedur Lemhannas.</p>
            <p className='mb-4 w-full md:w-[80%]'>Ketentuan tersebut memberikan landasan dan pedoman organisasi serta tata kerja Lemhannas, dengan tujuan agar Lemhannas dapat melakukan pembinaan dan pengkajian secara utuh segenap unsur kekuatan dan potensi nasional guna memelihara dan meningkatkan ketahanan nasional. Lebih jauh lagi, Lemhannas sebagai lembaga pengkajian dan pendidikan nasional yang menyelenggarakan pendidikan dan pengkajian berdasarkan konsepsi ketahanan nasional yang bekerjasama dengan badan pemerintahan dan non pemerintahan lain.</p>
        </div>

        <div className='w-full h-max mb-6 p-4 md:p-10'>
            <h2 className='font-bold text-[24px] w-full md:text-[36px] mb-4'>1982-1984: Dinamika Reorganisasi Lemhannas</h2>
            <p className='mb-4 w-full md:w-[80%]'>Sebagai realisasi Undang-undang Nomor 20 Tahun 1982 tanggal 19 September 1982 tentang Ketentuan-Ketentuan Pokok Pertahanan Keamanan Republik Indonesia, Pangab mengeluarkan Surat Keputusan Nomor : Kep/01/p/I/1984 tanggal 20 Januari 1984 tentang Pokok-Pokok Organisasi dan Prosedur Lembaga Pertahanan Nasional yang baru sebagai pengganti yang lama. Penyusunan kembali organisasi Lemhannas  tidak terlepas dari pelaksanaan reorganisasi ABRI secara keseluruhan yakni dipisahkannya jabatan Menhankam dan Pangab.</p>
            <p className='mb-4 w-full md:w-[80%]'>Reorganisasi ini dilakukan untuk memantapkan Lemhannas sebagai lembaga pengkajian dan pendidikan terutama dalam mengantisipasi perkembangan-perkembangan baru baik secara nasional, regional maupun global. Dengan keluarnya Surat Keputusan Pangab ini, Tugas Pokok Lemhannas adalah Membantu Panglima ABRI dalam menyelenggarakan pengkajian strategis dan pendidikan pemantapan dan pengembangan kader kepemimpinan nasional yang integratif.</p>
        </div>

        <div className='w-full h-max mb-6 p-4 md:p-10'>
            <h2 className='font-bold text-[24px] w-full md:text-[36px] mb-4'>1994: “Pertahanan” Menjadi “Ketahanan”</h2>
            <p className='mb-4 w-full md:w-[80%]'>Pada tanggal 2 Februari 1994, terjadi perubahan kedudukan (reposisi), Lemhannas yang diserahterimakan dari Mabes ABRI kepada Departemen Hankam, dengan demikian dimulai lagi periode baru yakni Lemhannas berada di bawah Menhankam dan Gubernur Lemhannas bertanggungjawab kepada Menhankam.</p>
            <p className='mb-4 w-full md:w-[80%]'>Bersamaan dengan itu kepanjangan ”Lembaga Pertahanan Nasional” diubah menjadi “Lembaga Ketahanan Nasional” dengan singkatan tetap Lemhannas, hanya  kata “Pertahanan” diganti menjadi “Ketahanan”.  Hal itu juga diperkukuh dengan Keppres RI nomor 4 tahun 1994 tentang Lembaga Ketahanan Nasional. Perubahan ini sama sekali tidak mengubah tugas pokok dan fungsi Lemhannas. Perubahan dimaksudkan agar Lemhannas lebih meningkatkan lagi peran dan fungsinya dalam menyelenggarakan tugas pokok yang diembannya.</p>
            <p className='mb-4 w-full md:w-[80%]'>Tuntutan lingkungan strategis membawa konsekuensi dan tanggung jawab yang lebih besar bagi Lemhannas. Oleh karena itu, tantangan tugas di masa mendatang bagi Lemhannas akan meningkat. Perubahan status dan kedudukan Lemhannas, tidak otomatis merubah struktur organisasi Lemhannas pada saat itu. Melalui kebijakan pemerintah RI, jabatan Menhankam RI dan Panglima ABRI dijabat oleh satu orang, maka dengan sendirinya Lemhannas berada di bawah Menhankam/Pangab.</p>
        </div>

        <div className='w-full h-max mb-6 p-4 md:p-10'>
            <h2 className='font-bold text-[24px] w-full md:text-[36px] mb-4'>1999-2001: Pertama Kali Lemhannas Dipimpin Pejabat Sipil</h2>
            <p className='mb-4 w-full md:w-[80%]'>Setelah reformasi, pemerintah melakukan berbagai perubahan sesuai tuntutan reformasi, antara lain perubahan Departemen Pertahanan dan Keamanan (Dephankam) menjadi Departemen Pertahanan (Dephan) Republik Indonesia, sedangkan Mabes ABRI berubah menjadi Mabes TNI. Dengan  perubahan ini, Lemhannas berada di bawah Dephan RI namun Struktur Organisasinya tetap, tidak berubah.</p>
            <p className='mb-4 w-full md:w-[80%]'>Pada Maret 2001, Presiden Abdurrahman Wahid mengeluarkan pernyataan berkaitan dengan Lemhannas berdasarkan Keputusan Presiden nomor 42 tahun 2001, tentang perubahan atas Keputusan Presiden nomor 166 tahun 2000 tentang Kedudukan, Tugas, Fungsi, Kewenangan, Susunan Organisasi dan Tata Kerja Lembaga Pemerintah Non Departemen, sebagaimana telah beberapa kali diubah terakhir dengan Keputusan Presiden nomor 16 tahun 2001, menyatakan secara tegas tentang tugas Lemhannas. Dengan keluarnya keputusan ini, Lemhannas dikeluarkan dari struktur organisasi Dephan dan harus melakukan restrukturisasi organisasi sebagai Lembaga Pemerintah Non Departemen (LPND). Dengan demikian sejak tahun 2001 kedudukan Lemhannas berada di bawah Presiden sebagai Lembaga Pemerintah Non Departemen (LPND).</p>
            <p className='mb-4 w-full md:w-[80%]'>Dengan perubahan tersebut, untuk pertama kalinya kepemimpinan Lemhannas juga menorehkan sejarah, karena untuk pertama kali Lembaga ini dipimpin oleh seorang pejabat sipil yang merintis kariernya dari PNS Golongan I yakni Prof. DR. Ermaya Suradinata, SH, MS yang sebelumnya menjabat sebagai Direktur Jenderal Pembinaan Kesatuan Bangsa dan Perlindungan Masyarakat, Departemen Dalam Negeri.</p>
            <p className='mb-4 w-full md:w-[80%]'>Diangkatnya Pegawai Negeri Sipil sebagai Gubernur Lemhannas, tidak terlepas dari gagasan awal sewaktu Lemhannas didirikan. Dalam sambutannya Presiden Soekarno yang menyatakan : “.....perang modern bukan sekedar perang militer, melainkan peperangan yang menyangkut seluruh unsur yang dimiliki rakyat. dengan demikian tidak hanya militer yang memperhatikan dan menyempurnakan ketahanan Indonesia, tetapi juga warga  sipil”.</p>
        </div>

        <div className='w-full h-max mb-6 p-4 md:p-10'>
            <h2 className='font-bold text-[24px] w-full md:text-[36px] mb-4'>2006-2010: Lemhannas Sebagai “Centre Of Excellent”</h2>
            <p className='mb-4 w-full md:w-[80%]'>Langkah ke depan harus menjadi lebih efisien, efektif, “inward and outward looking” dalam berfikir dan memenuhi standar internasional. Perubahan itu bisa berjalan dengan baik, jika Lemhannas dijadikan sebagai satu-satunya lembaga yang mendidik kader pimpinan nasional (centre of excelent) dan dikuti pengembangan organisasi dan sumber daya manusia (SDM) pendukungnya, aktualisasi doktrin “code of conduct” para pemegang peran, pengembangan dan pembinaan pribadi alumninya, partisipasi masyarakat dan kerjasama luar negeri, serta didukung “political will”  pemerintah.</p>
            <p className='mb-4 w-full md:w-[80%]'>Oleh karena itu, tak berlebihan jika Presiden Susilo Bambang Yudoyono saat itu meminta Lemhannas untuk menjadi Lembaga Kelas Dunia. Keinginan Presiden disambut dengan semangat tinggi oleh Gubernur Lemhanas RI Prof. DR. Muladi, SH yang siap merealisasikan perubahan itu. Maka dari itu, dengan paradigma barunya Lemhannas melakukan restrukturisasi dan revitalisasi untuk merubah Lemhannas menjadi lembaga prestisius dan berkelas dunia.</p>
            <p className='mb-4 w-full md:w-[80%]'>Perubahan yang terjadi dalam restrukturisasi kali ini cukup signifikan, karena telah dirumuskan visi dan misi baru menuju terbentuknya lembaga yang sekelas dengan lembaga-lembaga sejenis lainnya di luar negeri. Perubahan juga terjadi dalam tugas dan fungsi yang bertambah, yaitu fungsi pemantapan nilai-nilai kebangsaan dan fungsi kerjasama yang diperluas jangkauannya. Dibentuk pula Dewan Pengarah sebagai “Policy Making Body” untuk membantu Gubernur dalam mengendalikan kegiatan operasional Lemhannas, sedangkan Gubernur Lemhannas mendapatkan kedudukan dan perlakuan setingkat menteri berdasarkan Perpres Nomor 67 Tahun 2006.</p>
            <p className='mb-4 w-full md:w-[80%]'>Revitalisasi dan restrukturisasi kelembagaan direalisasikan melalui Peraturan Gubernur Lemhannas RI nomor 01 tahun 2006 tentang Tugas, Fungsi, Susunan Organisasi dan Tata Kerja Lembaga Ketahanan Nasional Republik Indonesia. Hal ini untuk menjawab keinginan Presiden Susilo Bambang Yudhoyono, yang menegaskan Lemhannas RI harus dapat menjadi Lembaga Kelas Dunia (World Class Institution).</p>
        </div>

        <div className='w-full h-max mb-6 p-4 md:p-10'>
            <h2 className='font-bold text-[24px] w-full md:text-[36px] mb-4'>2011-2016: Lemhannas Menuju World Class Institution</h2>
            <p className='mb-4 w-full md:w-[80%]'>Pada saat pelantikan Prof. Dr. Ir. Budi Susilo Soepandji, DEA sebagai Gubernur Lemhannas RI tanggal 17 Februari 2011 dan audiensi Gubernur Lemhannas RI yang didampingi pejabat teras Lemhannas RI pada  5 Agustus 2011, Presiden Susilo Bambang Yudhoyono menegaskan kembali harapan beliau agar Lemhannas RI mampu mengembangkan diri menjadi lembaga pendidikan dan kajian yang memiliki standar sebagai lembaga kelas dunia (World Class Institution).</p>
            <p className='mb-4 w-full md:w-[80%]'>Dalam kesempatan pembekalan peserta PPRA XLVI di Istana Wakil Presiden RI pada tanggal 17 November 2011, Wakil Presiden RI, Prof. Dr. Boediono, M. Ec, menyampaikan arahan dan harapan yang sama terkait rencana Lemhannas RI menuju Lembaga Kelas Dunia. Wakil Presiden RI juga mengharapkan agar Lemhannas RI mencermati perkembangan lingkungan strategis dalam dan luar negeri yang mempengaruhi kehidupan nasional, seperti isu Globalisasi, Demokrasi, Nasionalisme dan Leadership (Kepemimpinan).</p>
            <p className='mb-4 w-full md:w-[80%]'>Gubernur Lemhannas RI merespons keinginan Presiden untuk menjadikan Lemhannas sebagai World Class Institution,  lembaga pendidikan, pengkajian, dan pemantapan nilai-nilai kebangsaan yang dapat menjadi rujukan nasional, regional dan global dengan membentuk pentahapan pembangunan Lemhannas RI.</p>
            <p className='mb-4 w-full md:w-[80%]'>Pada  2010, kegiatan  pendidikan dan hasil kajian Lemhannas RI ditargetkan  menjadi rujukan nasional, kemudian pada 2015, menjadi rujukan regional ASEAN dan selanjutnya, pada 2020  menjadi rujukan regional Asia Pasifik, sedangkan  2025 merupakan langkah panjang menuju pencapaian akhir yakni menjadi rujukan dunia, sehingga diperlukan langkah strategis dan kerja keras segenap jajaran  Lemhannas RI. Untuk itu Lemhannas RI melakukan 11 Prinsip Pembaharuan, Revitalisasi dan Restrukturisasi Organisasi, Reformasi Birokrasi, Strengthening the Capacity Building, dan Lemhannas Social Network.</p>
        </div>

        <div className='w-full h-max mb-6 p-4 md:p-10'>
            <h2 className='font-bold text-[24px] w-full md:text-[36px] mb-4'>2022-Sekarang: Transformasi Lemhannas Menuju Indonesia 2045</h2>
            <p className='mb-4 w-full md:w-[80%]'>Andi Widjajanto yang dilantik Presiden RI Joko Widodo menjadi Gubernur ke-17 Lemhannas RI pada 21 Februari 2022 mendapatkan arahan untuk melanjutkan transformasi Lemhannas RI. Presiden berharap Lemhannas RI mampu menjawab berbagai tantangan geopolitik yang akan dihadapi menuju Indonesia 2045. Beragam penyesuaian dilakukan untuk peningkatan akuntabilitas pelaksanaan tugas dan fungsi konstitusional yang dimiliki Lemhannas RI. Hal tersebut terwujud dalam amplifikasi kualitas kajian strategis yang dibutuhkan Presiden RI dalam menentukan kebijakan strategis dalam lingkup nasional, regional, hingga global.</p>
            <p className='mb-4 w-full md:w-[80%]'>Selain itu, pengembangan metodologi dan pedagogi pendidikan bagi calon-calon pemimpin nasional serta memperluas jangkauan pemantapan nilai-nilai kebangsaan juga menjadi perhatian utama dalam transformasi Lemhannas RI. Dengan semakin tingginya benchmark yang telah disepakati, ke depannya Lemhannas RI diharapkan menjadi world class institution yang menjadi rujukan dunia dalam bidang ketahanan nasional.</p>
        </div>

        <Footer />
    </div>
  )
}

export default Sejarah
